# Generated by Django 3.2 on 2024-12-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoneApp', '0002_contactinquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['id']},
        ),
    ]
